spring.application.name=apigateway
server.port=9090


# autenticacion
spring.cloud.gateway.routes[0].id=autenticacion
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# admin
spring.cloud.gateway.routes[1].id=admin
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/**

spring.cloud.gateway.routes[2].id=pacientes-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/paciente/**

# paciente CRUD
spring.cloud.gateway.routes[9].id=pacientes-crud
spring.cloud.gateway.routes[9].uri=http://localhost:8083
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/pacientes/**

# lista-espera
spring.cloud.gateway.routes[3].id=lista-espera
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/lista-espera/**

# agenda - bloques horarios
spring.cloud.gateway.routes[4].id=agenda-bloques
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/bloques/**

# agenda - doctores
spring.cloud.gateway.routes[5].id=agenda-doctor
spring.cloud.gateway.routes[5].uri=http://localhost:8085
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/doctor/**

# agenda - especialidades
spring.cloud.gateway.routes[6].id=agenda-especialidad
spring.cloud.gateway.routes[6].uri=http://localhost:8085
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/especialidad/**

# agenda - especialidad-doctor
spring.cloud.gateway.routes[7].id=agenda-esp-doc
spring.cloud.gateway.routes[7].uri=http://localhost:8085
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/doctorEspecialidad/**

# agenda - sexo
spring.cloud.gateway.routes[8].id=agenda-sexo
spring.cloud.gateway.routes[8].uri=http://localhost:8085
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/sexo/**

# agenda - citas
spring.cloud.gateway.routes[10].id=agenda-citas
spring.cloud.gateway.routes[10].uri=http://localhost:8085
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/citas/**

# agenda - disponibilidad doctor
spring.cloud.gateway.routes[11].id=agenda-disponibilidad
spring.cloud.gateway.routes[11].uri=http://localhost:8085
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/disponibilidad/**

# CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=Authorization,Content-Type,Accept
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true