server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd-admin}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.application.name=admin-service

jwt.secret=${JWT_SECRET:MiClaveSecretaParaJWT2026RedNorteClinicaDebeSerLargaYCompletaParaMayorSeguridad123456}
jwt.expiration=${JWT_EXPIRATION:3600000}
